version: '3.7'

# Networks
networks:
    # Internal network
    internal:
        driver: bridge

volumes:
    miniERP-mysql_data:
        driver: local

# Services
services:

    # Nginx
    miniERP-nginx:
        image: webdevops/php-nginx-dev:8.4-alpine
        container_name: miniERP-nginx
        networks:
            - internal
        working_dir: /var/www
        volumes:
            - .:/var/www
            - .docker/opt/docker/etc/supervisor.d/php-fpm.conf:/opt/docker/etc/supervisor.d/php-fpm.conf
        ports:
            - "80:80"
        environment:
            - WEB_DOCUMENT_ROOT=/var/www/public
            - WEB_DOCUMENT_INDEX=index.php

    miniERP-mysql:
        image: mysql:8.2
        container_name: miniERP-mysql
        networks:
            - internal
        volumes:
            - miniERP-mysql_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - "3306:3306"
